Add turkish locales
Lennoard/SysctlGUI pull request #62
Opened 2024-03-31 13:55 UTC by mikropsoft

2024-04-01 23:53 UTC, Lennoard commented
@mikropsoft thank you very much for your contribution. Unfortunately, some strange thing is happening that prevents the building the app with your additions. It is most likely related to illegal unicode characters the compiler can't allow.

- `res/values-tr/strings.xml` line 23
- `res/values-tr/params_info.xml` line 30

Suggestion: simplify characters in these lines.

2024-04-01 23:54 UTC, Lennoard requested changes

2024-04-01 23:54 UTC, Lennoard commented on app/src/main/res/values-tr/strings.xml
> +    <string name="browse_variables_sum">Belirli bir çekirdek parametresi için /proc/sys'ye göz atın</string>
This string resource contains an unescaped apostrophe (`'`)

Same for lines [92 and 93](https://github.com/Lennoard/SysctlGUI/pull/62/files#diff-11548b2158b255e354ac7ab1cdc4dc4bf1d0cb372bbf1425508d86d35b69ed50R92-R93)

Suggestion: fix apostrophe escaping by using a `\` character before each.

2024-04-01 23:54 UTC, Lennoard commented on app/src/main/res/values-tr/params_info.xml
> +    <string name="compact_unevictable_allowed">Yalnızca CONFIG_COMPACTION ayarlandığında kullanılabilir. 1 olarak ayarlandığında, sıkıştırmanın sayfaların sıkıştırılması için kaçınılmaz lru'yu (kilit
This string resource contains an unescaped apostrophe (`'`).
Same for lines 10, 13, 15, 16, 20, 21, 22, 27, 29, 30 and 32.

Suggestion: fix apostrophe escaping by using a `\` character before each.

2024-04-02 14:06 UTC, Lennoard approved these changes
Looking good!

2024-04-02 14:07 UTC, mikropsoft commented
> Looking good!

Good luck 💯

2024-04-12 01:01 UTC, merged